[tools]
# generic
neovim = "0.12.5"
fd = "10.5.0"
tree-sitter = "0.27.0"
usage = "6.9.0"
lazygit = "0.65.1"
lazydocker = "0.25.2"
fzf = "0.74.4"
task = "3.53.1"
just = "1.58.0"
jq = "1.8.2"
yq = "4.53.6"
bat = "0.26.1"
fx = "39.2.0"
# lua
lua-language-server = "3.19.1"
stylua = "2.5.2"
# toml
tombi = "1.5.5"
# go
go = "1.27.1"
"go:golang.org/x/tools/gopls" = "0.23.0"
"go:gotest.tools/gotestsum" = "1.13.0"
"go:github.com/go-delve/delve/cmd/dlv" = "1.27.2"
# js/ts
node = "26.8.2"
bun = "1.4.2"
"npm:@vtsls/language-server" = "0.3.0"
"aqua:biomejs/biome" = "2.5.13"
# json/css/html
"npm:vscode-langservers-extracted" = "4.10.0"
# yaml
"npm:yaml-language-server" = "1.24.0"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "0.21.0"
# python
"pipx:ipython" = "9.17.1"
uv = "0.12.13"
ruff = "0.16.7"
"pipx:basedpyright" = "1.40.1"
# protobuf
buf = "1.73.0"
# zig
zig = "0.16.0"
zls = "0.16.0"
# rust
rust = { version = "1.98.1", components = ["rust-analyzer", "clippy"] }
# generic things that require something from above
"npm:hunkdiff" = "0.22.0"
"github:latex-lsp/texlab" = "5.26.0"
