[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = ""

[icons]
name = "awesome5"
[icons.overrides]

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "networkmanager"
device_format = "{icon}{ap}"
on_click = "kitty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "battery"
device = "BAT0"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "bluetooth"
format = "bose"
format_unavailable = "bose"
mac = "28:11:A5:32:63:57"

[[block]]
block = "bluetooth"
format = "sbose"
format_unavailable = "sbose"
mac = "4C:87:5D:80:C3:28"
hide_disconnected = true

[[block]]
block = "bluetooth"
format = "JBL"
format_unavailable = "JBL"
mac = "B8:F6:53:9E:17:FE"
hide_disconnected = true

[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pavucontrol"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
format = "{layout}"

[[block]]
block = "time"
interval = 60
format = "%a %d %b %R"