# yaml-language-server: $schema=schema.json
inherit:
  - posix
apps:
  - name: ghostty
    paths:
      - system: $HOME/.config/ghostty/config
        repo: config
  - name: hammerspoon
    paths:
      - system: $HOME/.hammerspoon/init.lua
        repo: init.lua
      - system: $HOME/.hammerspoon/utils.lua
        repo: utils.lua
      - system: $HOME/.hammerspoon/.luarc.json
        repo: dotluarc.json
      - system: $HOME/.hammerspoon/biome.json
        repo: biome.json
