- system: $HOME/.config/nvim/init.lua
  repo: init.lua
- system: $HOME/.config/nvim/filetype.lua
  repo: filetype.lua
- system: $HOME/.config/nvim/after
  repo: after
- system: $HOME/.config/nvim/lsp
  repo: lsp
- system: $HOME/.config/nvim/lua
  repo: lua
- system: $HOME/.config/nvim/queries
  repo: queries
- system: $HOME/.config/nvim/lazy-lock.json
  repo: lazy-lock.json
