#!/usr/bin/env sh

dotfiles linux binscripts load
dotfiles shared neovim load
dotfiles shared starship load
dotfiles shared zsh load
dotfiles linux ghostty load
dotfiles linux sway load
dotfiles linux waybar load
dotfiles linux wofi load
